api:
  dashboard: true

entryPoints:
  web:
    address: ":8880"
  websecure:
    address: ":8444"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${LETSENCRYPT_EMAIL}
      storage: /letsencrypt/acme.json
      tlsChallenge: true
